### ISSUE TITLE
Doesn't work in production

### ISSUE THREAD

**Issue by elie222** [bondz/react-epic-spinners#1]
Any idea why this would work for us in development but not when we deploy?

For one person it even works on Chrome when we deploy to prod, but for most it doesn't. Any ideas?

**Comment by bondz** [comment]
Can you give me an idea of what you mean by deploy to production? The demo site is built with CRA with `webpack` in `production` settings.

It'll help if I can understand how you're building the library for production.

**Comment by elie222** [comment]
Yes exactly. CRA with webpack in production

**Comment by bondz** [comment]
Can you create a repo with the code that reproduces the problem?

**Comment by MateusGabi** [comment]
Same thing! 

At version `0.3.0`. I'm was at `0.2.1`, but when I upgrade to `0.3.0`.

```
app/containers/BrandForm/tests/index.test.js
  ● Test suite failed to run

    Cannot find module 'react-epic-spinners' from 'Overlay.js'

      1 | import PropTypes from 'prop-types';
      2 | import React from 'react';
    > 3 | import { HalfCircleSpinner } from 'react-epic-spinners';
        | ^
      4 | import LoadingOverlay from 'react-loading-overlay';
      5 | import styled from 'styled-components';
      6 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (app/components/Loading/Overlay.js:3:1)
```

**Comment by bondz** [comment]
@MateusGabi Did it work in production at 0.2.1?

**Comment by MateusGabi** [comment]
@bondz Yes.

**Comment by bondz** [comment]
@MateusGabi @elie222  Any chance I can get the dependencies installed in your package.json file?

**Comment by MateusGabi** [comment]
```
{
  "name": "XXXXX",
  "version": "XXX",
  "description": "XXXXXX",
  "repository": {
    "type": "git",
    "url": "XXXXX"
  },
  "engines": {
    "npm": ">=5",
    "node": ">=8.10.0"
  },
  "author": "XXXXX",
  "license": "XXXXX",
  "scripts": {
    "analyze:clean": "rimraf stats.json",
    "preanalyze": "npm run analyze:clean",
    "analyze": "node ./internals/scripts/analyze.js",
    "extract-intl": "node ./internals/scripts/extract-intl.js",
    "npmcheckversion": "node ./internals/scripts/npmcheckversion.js",
    "preinstall": "npm run npmcheckversion",
    "prebuild": "npm run build:clean",
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout",
    "build:clean": "rimraf ./build",
    "start": "cross-env NODE_ENV=development node server",
    "start:tunnel": "cross-env NODE_ENV=development ENABLE_TUNNEL=true node server",
    "start:production": "npm run test && npm run build && npm run start:prod",
    "start:prod": "cross-env NODE_ENV=production node server",
    "presetup": "npm i chalk shelljs",
    "setup": "node ./internals/scripts/setup.js",
    "clean": "shjs ./internals/scripts/clean.js",
    "clean:all": "npm run analyze:clean && npm run test:clean && npm run build:clean",
    "generate": "plop --plopfile internals/generators/index.js",
    "lint": "npm run lint:js",
    "lint:css": "stylelint './app/**/*.js'",
    "lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts",
    "lint:eslint:fix": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts --fix",
    "lint:js": "npm run lint:eslint -- . ",
    "lint:staged": "lint-staged",
    "pretest": "npm run test:clean && npm run lint",
    "test:clean": "rimraf ./coverage",
    "test": "cross-env NODE_ENV=test jest --coverage",
    "test:watch": "cross-env NODE_ENV=test jest --watchAll",
    "coveralls": "cat ./coverage/lcov.info | coveralls",
    "prettify": "prettier --write"
  },
  "lint-staged": {
    "*.js": [
      "npm run lint:eslint:fix",
      "git add --force"
    ],
    "*.json": [
      "prettier --write",
      "git add --force"
    ]
  },
  "resolutions": {
    "babel-core": "7.0.0-bridge.0"
  },
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "@sentry/browser": "^4.6.4",
    "@u-wave/react-vimeo": "^0.6.0",
    "animate.css": "^3.7.0",
    "chalk": "^2.4.2",
    "compression": "1.7.3",
    "connected-react-router": "^5.0.1",
    "cross-env": "5.2.0",
    "eskolare-ui-dashboard": "^0.1.20",
    "express": "4.16.4",
    "fontfaceobserver": "^2.1.0",
    "format-currency-to-br": "^1.0.0",
    "formik": "^1.5.1",
    "glob": "^7.1.3",
    "history": "4.7.2",
    "hoist-non-react-statics": "^3.3.0",
    "humanize-plus": "^1.8.2",
    "immutable": "3.8.2",
    "intl": "1.2.5",
    "invariant": "2.2.4",
    "ip": "1.1.5",
    "libphonenumber-js": "^1.7.9",
    "loadable-components": "2.2.3",
    "lodash": "4.17.11",
    "minimist": "1.2.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.3",
    "react-bootstrap-sweetalert": "^4.4.1",
    "react-bootstrap-switch": "^15.5.3",
    "react-datetime": "^2.16.3",
    "react-dom": "^16.8.3",
    "react-epic-spinners": "0.2.1",
    "react-facebook-login": "^4.1.1",
    "react-google-login": "^4.0.1",
    "react-google-tag-manager": "^2.2.1",
    "react-helmet": "5.2.0",
    "react-hot-loader": "^4.7.1",
    "react-input-mask": "^2.0.4",
    "react-intl": "^2.8.0",
    "react-loadable": "^5.5.0",
    "react-loading-overlay": "^1.0.1",
    "react-notification-alert": "0.0.9",
    "react-notifications-indicator": "^1.0.3",
    "react-quill": "^1.3.3",
    "react-redux": "^5.1.1",
    "react-router": "^4.3.1",
    "react-router-dom": "4.3.1",
    "react-select": "^2.4.1",
    "react-youtube": "^7.9.0",
    "reactstrap": "^7.1.0",
    "redux": "4.0.1",
    "redux-auth-wrapper": "^2.1.0",
    "redux-immutable": "4.0.0",
    "redux-saga": "0.16.2",
    "reselect": "4.0.0",
    "sanitize.css": "^8.0.0",
    "styled-components": "^4.1.3",
    "superagent": "^4.1.0",
    "warning": "^4.0.3",
    "yup": "^0.26.7"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.3",
    "@babel/plugin-proposal-class-properties": "^7.3.3",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.2.0",
    "@babel/plugin-transform-react-constant-elements": "^7.2.0",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "7.0.0",
    "@babel/register": "7.0.0",
    "@sentry/cli": "^1.39.1",
    "@sentry/webpack-plugin": "^1.6.2",
    "add-asset-html-webpack-plugin": "^3.1.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-dynamic-import-node": "2.2.0",
    "babel-plugin-lodash": "3.3.4",
    "babel-plugin-react-intl": "3.0.1",
    "babel-plugin-react-transform": "3.0.0",
    "babel-plugin-styled-components": "^1.10.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "circular-dependency-plugin": "5.0.2",
    "compare-versions": "3.4.0",
    "compression-webpack-plugin": "2.0.0",
    "coveralls": "^3.0.3",
    "css-loader": "^1.0.1",
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.10.0",
    "enzyme-to-json": "^3.3.5",
    "eslint": "^5.14.1",
    "eslint-config-airbnb": "17.1.0",
    "eslint-config-airbnb-base": "13.1.0",
    "eslint-config-prettier": "^3.5.0",
    "eslint-import-resolver-webpack": "^0.11.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-redux-saga": "^0.10.0",
    "file-loader": "^3.0.1",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "image-webpack-loader": "^4.6.0",
    "imports-loader": "0.8.0",
    "jest-cli": "23.6.0",
    "jest-styled-components": "^6.3.1",
    "lint-staged": "^8.1.4",
    "ngrok": "^3.1.1",
    "node-plop": "^0.17.4",
    "null-loader": "0.1.1",
    "offline-plugin": "^5.0.6",
    "plop": "^2.2.1",
    "pre-commit": "1.2.2",
    "prettier": "^1.16.4",
    "react-app-polyfill": "^0.2.1",
    "react-test-renderer": "^16.8.3",
    "rimraf": "^2.6.3",
    "shelljs": "^0.8.3",
    "style-loader": "0.23.1",
    "stylelint": "^9.10.0",
    "stylelint-config-recommended": "2.1.0",
    "stylelint-config-styled-components": "0.1.1",
    "stylelint-processor-styled-components": "^1.5.2",
    "svg-url-loader": "2.3.2",
    "terser-webpack-plugin": "^1.2.3",
    "url-loader": "1.1.2",
    "webpack": "^4.29.5",
    "webpack-assets-manifest": "^3.1.1",
    "webpack-cli": "^3.2.3",
    "webpack-dev-middleware": "^3.6.0",
    "webpack-hot-middleware": "2.24.3 ",
    "webpack-pwa-manifest": "^4.0.0",
    "whatwg-fetch": "3.0.0"
  }
}
```

**Comment by bondz** [comment]
Thank you so much. Will get back to you. 




Get Outlook for Android







On Wed, Mar 13, 2019 at 5:00 PM +0100, "Mateus Gabi" <notifications@github.com> wrote:










{
  "name": "XXXXX",
  "version": "XXX",
  "description": "XXXXXX",
  "repository": {
    "type": "git",
    "url": "XXXXX"
  },
  "engines": {
    "npm": ">=5",
    "node": ">=8.10.0"
  },
  "author": "XXXXX",
  "license": "XXXXX",
  "scripts": {
    "analyze:clean": "rimraf stats.json",
    "preanalyze": "npm run analyze:clean",
    "analyze": "node ./internals/scripts/analyze.js",
    "extract-intl": "node ./internals/scripts/extract-intl.js",
    "npmcheckversion": "node ./internals/scripts/npmcheckversion.js",
    "preinstall": "npm run npmcheckversion",
    "prebuild": "npm run build:clean",
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout",
    "build:clean": "rimraf ./build",
    "start": "cross-env NODE_ENV=development node server",
    "start:tunnel": "cross-env NODE_ENV=development ENABLE_TUNNEL=true node server",
    "start:production": "npm run test && npm run build && npm run start:prod",
    "start:prod": "cross-env NODE_ENV=production node server",
    "presetup": "npm i chalk shelljs",
    "setup": "node ./internals/scripts/setup.js",
    "clean": "shjs ./internals/scripts/clean.js",
    "clean:all": "npm run analyze:clean && npm run test:clean && npm run build:clean",
    "generate": "plop --plopfile internals/generators/index.js",
    "lint": "npm run lint:js",
    "lint:css": "stylelint './app/**/*.js'",
    "lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts",
    "lint:eslint:fix": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts --fix",
    "lint:js": "npm run lint:eslint -- . ",
    "lint:staged": "lint-staged",
    "pretest": "npm run test:clean && npm run lint",
    "test:clean": "rimraf ./coverage",
    "test": "cross-env NODE_ENV=test jest --coverage",
    "test:watch": "cross-env NODE_ENV=test jest --watchAll",
    "coveralls": "cat ./coverage/lcov.info | coveralls",
    "prettify": "prettier --write"
  },
  "lint-staged": {
    "*.js": [
      "npm run lint:eslint:fix",
      "git add --force"
    ],
    "*.json": [
      "prettier --write",
      "git add --force"
    ]
  },
  "resolutions": {
    "babel-core": "7.0.0-bridge.0"
  },
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "@sentry/browser": "^4.6.4",
    "@u-wave/react-vimeo": "^0.6.0",
    "animate.css": "^3.7.0",
    "chalk": "^2.4.2",
    "compression": "1.7.3",
    "connected-react-router": "^5.0.1",
    "cross-env": "5.2.0",
    "eskolare-ui-dashboard": "^0.1.20",
    "express": "4.16.4",
    "fontfaceobserver": "^2.1.0",
    "format-currency-to-br": "^1.0.0",
    "formik": "^1.5.1",
    "glob": "^7.1.3",
    "history": "4.7.2",
    "hoist-non-react-statics": "^3.3.0",
    "humanize-plus": "^1.8.2",
    "immutable": "3.8.2",
    "intl": "1.2.5",
    "invariant": "2.2.4",
    "ip": "1.1.5",
    "libphonenumber-js": "^1.7.9",
    "loadable-components": "2.2.3",
    "lodash": "4.17.11",
    "minimist": "1.2.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.3",
    "react-bootstrap-sweetalert": "^4.4.1",
    "react-bootstrap-switch": "^15.5.3",
    "react-datetime": "^2.16.3",
    "react-dom": "^16.8.3",
    "react-epic-spinners": "0.2.1",
    "react-facebook-login": "^4.1.1",
    "react-google-login": "^4.0.1",
    "react-google-tag-manager": "^2.2.1",
    "react-helmet": "5.2.0",
    "react-hot-loader": "^4.7.1",
    "react-input-mask": "^2.0.4",
    "react-intl": "^2.8.0",
    "react-loadable": "^5.5.0",
    "react-loading-overlay": "^1.0.1",
    "react-notification-alert": "0.0.9",
    "react-notifications-indicator": "^1.0.3",
    "react-quill": "^1.3.3",
    "react-redux": "^5.1.1",
    "react-router": "^4.3.1",
    "react-router-dom": "4.3.1",
    "react-select": "^2.4.1",
    "react-youtube": "^7.9.0",
    "reactstrap": "^7.1.0",
    "redux": "4.0.1",
    "redux-auth-wrapper": "^2.1.0",
    "redux-immutable": "4.0.0",
    "redux-saga": "0.16.2",
    "reselect": "4.0.0",
    "sanitize.css": "^8.0.0",
    "styled-components": "^4.1.3",
    "superagent": "^4.1.0",
    "warning": "^4.0.3",
    "yup": "^0.26.7"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.3",
    "@babel/plugin-proposal-class-properties": "^7.3.3",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.2.0",
    "@babel/plugin-transform-react-constant-elements": "^7.2.0",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "7.0.0",
    "@babel/register": "7.0.0",
    "@sentry/cli": "^1.39.1",
    "@sentry/webpack-plugin": "^1.6.2",
    "add-asset-html-webpack-plugin": "^3.1.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-dynamic-import-node": "2.2.0",
    "babel-plugin-lodash": "3.3.4",
    "babel-plugin-react-intl": "3.0.1",
    "babel-plugin-react-transform": "3.0.0",
    "babel-plugin-styled-components": "^1.10.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "circular-dependency-plugin": "5.0.2",
    "compare-versions": "3.4.0",
    "compression-webpack-plugin": "2.0.0",
    "coveralls": "^3.0.3",
    "css-loader": "^1.0.1",
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.10.0",
    "enzyme-to-json": "^3.3.5",
    "eslint": "^5.14.1",
    "eslint-config-airbnb": "17.1.0",
    "eslint-config-airbnb-base": "13.1.0",
    "eslint-config-prettier": "^3.5.0",
    "eslint-import-resolver-webpack": "^0.11.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-redux-saga": "^0.10.0",
    "file-loader": "^3.0.1",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "image-webpack-loader": "^4.6.0",
    "imports-loader": "0.8.0",
    "jest-cli": "23.6.0",
    "jest-styled-components": "^6.3.1",
    "lint-staged": "^8.1.4",
    "ngrok": "^3.1.1",
    "node-plop": "^0.17.4",
    "null-loader": "0.1.1",
    "offline-plugin": "^5.0.6",
    "plop": "^2.2.1",
    "pre-commit": "1.2.2",
    "prettier": "^1.16.4",
    "react-app-polyfill": "^0.2.1",
    "react-test-renderer": "^16.8.3",
    "rimraf": "^2.6.3",
    "shelljs": "^0.8.3",
    "style-loader": "0.23.1",
    "stylelint": "^9.10.0",
    "stylelint-config-recommended": "2.1.0",
    "stylelint-config-styled-components": "0.1.1",
    "stylelint-processor-styled-components": "^1.5.2",
    "svg-url-loader": "2.3.2",
    "terser-webpack-plugin": "^1.2.3",
    "url-loader": "1.1.2",
    "webpack": "^4.29.5",
    "webpack-assets-manifest": "^3.1.1",
    "webpack-cli": "^3.2.3",
    "webpack-dev-middleware": "^3.6.0",
    "webpack-hot-middleware": "2.24.3 ",
    "webpack-pwa-manifest": "^4.0.0",
    "whatwg-fetch": "3.0.0"
  }
}

**Comment by mvolkmann** [comment]
I am hitting this same issue now.

**Comment by mvolkmann** [comment]
I just verified that my React Jest tests work fine with version 0.2.1, but fail with 0.3.0. With 0.3.0 imports from react-epic-spinners fail to find the library even though "npm install" installs it.

**Comment by manelgarcia** [comment]
this is still an issue isn't it?

**Comment by bondz** [comment]
I published 0.4.x, can you try that and let me know?

@mvolkmann I believe your issues should be fixed by that version.

**Comment by manelgarcia** [comment]
It's fixed now. Thanks.
